In [2]:
import os 
os.environ["CUDA_VISIBLE_DEVICES"]= '3'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import DepthwiseConv2D

NotFoundError: /home/mazin/.local/lib/python3.9/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

In [ ]:
dconv = DepthwiseConv2D(kernel_size=1, use_bias=False, depthwise_initializer='ones')
a = np.ones((1, 2, 2, 4))
filter = np.ones((1,1,4,4))
filter[:, :, :, 0] = 6
filter[:, :, :, 3] = 2
dconv.convolution_op(a, filter)/4

2022-02-19 14:11:20.413479: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [3]:
a = np.ones((1, 2, 2, 4))
filter = np.ones((1,1,4,1)) # Size of kernel is (h, w, input channels, channel mult)
att_weights = np.array([6, 1, 1, 3])
filter[0, 0, :, 0] = att_weights
tf.nn.depthwise_conv2d(a, filter, [1, 1, 1, 1], 'VALID')

<tf.Tensor: shape=(1, 2, 2, 4), dtype=float64, numpy=
array([[[[6., 1., 1., 3.],
         [6., 1., 1., 3.]],

        [[6., 1., 1., 3.],
         [6., 1., 1., 3.]]]])>

In [2]:
from layers import AttentionLayer

In [8]:
att_lay = AttentionLayer()
input = tf.Variable(np.ones((2, 2, 2, 4)), dtype=tf.float32)
out1 = att_lay(input)
print(out1) # It now knows the input shape channels is 4
att_lay.set_weights([np.array([3,1,1,5])])
out2 = att_lay(input)
print(out2) # Apply new attention weights per channel 

tf.Tensor(
[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]], shape=(2, 2, 2, 4), dtype=float32)
tf.Tensor(
[[[[3. 1. 1. 5.]
   [3. 1. 1. 5.]]

  [[3. 1. 1. 5.]
   [3. 1. 1. 5.]]]


 [[[3. 1. 1. 5.]
   [3. 1. 1. 5.]]

  [[3. 1. 1. 5.]
   [3. 1. 1. 5.]]]], shape=(2, 2, 2, 4), dtype=float32)


In [6]:
b = tf.Variable(att_weights)
b[tf.newaxis, tf.newaxis, :, tf.newaxis]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int64, numpy=
array([[[[6],
         [1],
         [1],
         [3]]]])>